name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      # For custom domain or root deployment, use base-href "/"
      - run: npm run build -- --configuration production --base-href "/"

      # Always use dist/xamplify-v2-frontend as the output directory
      - name: List build output
        run: ls -lR ${{ github.workspace }}/dist
      - name: Copy SPA fallback (404.html)
        run: cp dist/xamplify-v2-frontend/index.html dist/xamplify-v2-frontend/404.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/xamplify-v2-frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
